Repository sizzlemctwizzle/GM_config, pull requests merged in 2023-05, with the labels that each got.

#111 GM_config as constructor
  gm_config.js
Labels: Will Fix, Improvement, Feedback Needed

#114 Some JSHint fixes
  gm_config.js
Labels: Bugfix, Improvement

#116 Some more JSHint fixes (semicolons)
  gm_config.js
Labels: Improvement, Migration

#119 Bulk `let` ES migration
  gm_config.js
Labels: Improvement, Migration

#120 Fix missed init in bulk `let` convert
  gm_config.js
Labels: Bugfix

#121 Bleh... post #119
  gm_config.js
Labels: Bugfix

#123 Fixes a bug with forgotten and Unit Test
  gm_config.js
Labels: Bugfix
